spring:
  application:
    name: eureka-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/atliwen/MySpringCloudTest
          search-paths:
            - config-repo
          username: 499014099@qq.com
          password: qq123123