server:
  port: 2224

spring:
  application:
    name: ribbon-consumer

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://eureka-primary:8011/eureka/
      