spring:
  application:
    name: eureka-server-clustered

server:
  port: 1111
eureka:
  instance:
    hostname: eureka-primary
  client:
    serviceUrl:
      defaultZone: http://eureka-secondary:1112/eureka/,http://eureka-tertiary:1113/eureka/
      