spring:
  application:
    name: eureka-server-clustered
server:
  port: 1112
eureka:
  instance:
    hostname: eureka-secondary
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-primary:1111/eureka/,http://eureka-tertiary:1113/eureka/
    